
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 26 19:34:54 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LESS_OR_EQUEL = 26;
  public static final int CONST = 45;
  public static final int CHAR = 10;
  public static final int NOT_EQUAL = 22;
  public static final int CLOSE_PARENTHESES = 34;
  public static final int GREATER = 23;
  public static final int CONTINUE = 7;
  public static final int LESS = 24;
  public static final int MINUS = 17;
  public static final int SEMICOLON = 14;
  public static final int AND = 27;
  public static final int MULTUPLY = 18;
  public static final int OR = 28;
  public static final int BOOL = 12;
  public static final int COMMA = 13;
  public static final int CLASS = 39;
  public static final int INC = 30;
  public static final int DIV = 19;
  public static final int CLOSE_CHEVRONS = 38;
  public static final int PLUS = 16;
  public static final int ASSIGN = 29;
  public static final int IF = 2;
  public static final int DOT = 15;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int EQUAL = 21;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int NUMBER = 9;
  public static final int MOD = 20;
  public static final int IDENT = 46;
  public static final int BREAK = 4;
  public static final int VOID = 44;
  public static final int ELSE = 3;
  public static final int READ = 43;
  public static final int WHILE = 6;
  public static final int GREATER_OR_EQUEL = 25;
  public static final int PROG = 41;
  public static final int EXTENDS = 40;
  public static final int CLOSE_BRACES = 36;
  public static final int STRING = 11;
  public static final int DEC = 31;
  public static final int OPEN_PARENTHESES = 33;
  public static final int OPEN_CHEVRONS = 37;
  public static final int PRINT = 42;
  public static final int DO = 5;
  public static final int OPEN_BRACES = 35;
}

